PersonalWebsite/Controllers/GuestController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PersonalWebsite.Models;


namespace PersonalWebsite.Controllers
{
    public class GuestController : Controller
    {
        private GuestBook db = new GuestBook();

        
        // GET: Guest/Create
        public ActionResult Index()
        {
            //Sorts Comments by most recent and only return the first 20.
            var mostRecentEntries = (from entry in db.Entries orderby entry.DateAdded descending select entry).Take(20);

            var NumberOfComments = db.Entries.Count();

            ViewData["Count"] = NumberOfComments;
            ViewData["Comments"] = mostRecentEntries.ToList();
            return View();
        }

        // POST: Guest/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index([Bind(Include = "Id,Name,Message")] GuessBook guessBook)
        {
            if (ModelState.IsValid)
            {
                guessBook.DateAdded = DateTime.UtcNow;
                db.Entries.Add(guessBook);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(guessBook);
        }

        

        // GET: Guest/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GuessBook guessBook = db.Entries.Find(id);
            if (guessBook == null)
            {
                return HttpNotFound();
            }
            return View(guessBook);
        }

        // POST: Guest/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            GuessBook guessBook = db.Entries.Find(id);
            db.Entries.Remove(guessBook);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PersonalWebsite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html manifest="site.appcache">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @{

        // User First Visit, No Cookie or Session is Set yet
        if (Session["Theme"] == null & Request.Cookies["Theme"] == null)
        {
            ViewBag.ChangeTheme = "Would you like to change the theme?";

            //Set Theme to default Flatly settings
            <link rel="Stylesheet" href="@Url.Content("~/Themes/flatly.css")" />
        }

            // User Session Is Empty, but does have a Theme Cookie
        else if (Request.Cookies["Theme"] != null & Session["Theme"] == null)
        {
            var CookieTheme = Request.Cookies["Theme"].Value.ToString();

            //Set Session Theme to user Saved Theme stored in their cookie
            Session["Theme"] = (CookieTheme);

            <link rel="Stylesheet" href="@Url.Content("~/Themes/" + Session["Theme"])" />
        }


        else if (Request.Cookies["Theme"] == null)
        {
            ViewBag.ChangeTheme = "Would you like to change the theme?";
            <link rel="Stylesheet" href="@Url.Content("~/Themes/flatly.css")" />
        }


        else if (Session["Theme"] != null)
        {
            <link rel="Stylesheet" href="@Url.Content("~/Themes/" + Session["Theme"])" />
        }

        //Catches any errors some how if Session or Cookie not working
        else
        {
            <link rel="Stylesheet" href="@Url.Content("~/Themes/flatly.css")" />
        }

    }



</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Brian Keith Davis", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Websites", "Fav", "Home")</li>
                    <li>@Html.ActionLink("Books", "Books", "Home")</li>
                    <li>@Html.ActionLink("Photos", "Photos", "Home")</li>
                    <li>@Html.ActionLink("Guest Book", "Index", "Guest")</li>
                    <li>@Html.ActionLink("Change Theme", "Settings", "Home")</li>
                    <li>@Html.ActionLink("Login", "Login", "Home")</li>
                </ul>

            </div>
        </div>
    </div>
    <div class="container body-content">


        @RenderBody()

        <div class="clearfix"></div>

        <footer>
            <p>&copy; @DateTime.Now.Year - Brian Keith Davis</p>
        </footer>
    </div>

   
    @*Takes Auto Complete off and first textbox default focus*@
    
     <script type="text/javascript">

    $(document).ready(function ()
    {
        $("input:text,form").attr("autocomplete", "off");
        $("input[type=text]").first().focus();

    }
    )

    </script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>